/*COPYRIGHT WARNING:THIS PROGRAM IS PROTECTED BY THE NIGERIA COPYRIGHT LAW.
THEREFORE NO PART OF THIS PROGRAM SHOULD BE COPIED OR EDITED OR TRANSFERED OR USED BY ANY OTHER PERSON.
EXCEPT GIVEN AUTHOURISED PERMISSION FROM THE PROGRAMMER AFONJA OMOTOMIWA RAHEEM.
THE RIGHTFUL OWNER OF THIS PROGRAM...THANKS

THIS PROGRAM WISHES MY MUM HAPPY BIRTHDAY*/

class birthday{ 
	public static void main(String[] args) {
		int date, month, year;
		date = 1;
		month = 5;
		year = 2015;

		if (date == 1 && month == 5 && year == 2015) {
			System.out.println("HAPPY BIRTHDAY TO YOU MUM..WISHING YOU LONGLIFE AND PROSPERITY..LOVE YOU SO MUCH MA");
		}else{
			System.out.println("THAT'S NOT MY MUM'S BIRTHDAY DATE");
		}
	}
}
